<a href="https://colab.research.google.com/github/rieckace/AI-Agent-Sample-/blob/master-branch/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
a = pd.read_csv("/content/SOCR-HeightWeight.csv")

In [ ]:
display(a.head())

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

from matplotlib import pyplot as plt
_df_0['Index'].plot(kind='hist', bins=20, title='Index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['Height(Inches)'].plot(kind='hist', bins=20, title='Height(Inches)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['Weight(Pounds)'].plot(kind='hist', bins=20, title='Weight(Pounds)')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='Index', y='Height(Inches)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='Height(Inches)', y='Weight(Pounds)', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Index']
  ys = series['Height(Inches)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('Index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Index')
_ = plt.ylabel('Height(Inches)')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Index']
  ys = series['Weight(Pounds)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('Index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Index')
_ = plt.ylabel('Weight(Pounds)')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Index'}, axis=1)
              .sort_values('Index', ascending=True))
  xs = counted['Index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('Index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_8['Index'].plot(kind='line', figsize=(8, 4), title='Index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['Height(Inches)'].plot(kind='line', figsize=(8, 4), title='Height(Inches)')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['Weight(Pounds)'].plot(kind='line', figsize=(8, 4), title='Weight(Pounds)')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
a.head()

   Index  Height(Inches)  Weight(Pounds)
0      1        65.78331        112.9925
1      2        71.51521        136.4873
2      3        69.39874        153.0269
3      4        68.21660        142.3354
4      5        67.78781        144.2971

In [ ]:
x = a[["Height(Inches)"]]
y = a["Weight(Pounds)"]

In [ ]:
x.head()

   Height(Inches)
0        65.78331
1        71.51521
2        69.39874
3        68.21660
4        67.78781

In [ ]:
y.head()

0    112.9925
1    136.4873
2    153.0269
3    142.3354
4    144.2971
Name: Weight(Pounds), dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin = LinearRegression()

In [ ]:
lin.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=lin.predict(x_test)

In [ ]:
y_pred

array([136.64480344, 127.72267402, 127.85236052, ..., 139.1599701 ,
       123.21915554, 137.24383743])

In [ ]:
y_pred.shape

(5000,)

In [ ]:
y_test.shape

(5000,)

In [ ]:
y_test

14694    133.8311
22211    126.6700
19253    126.9731
24724    145.0337
22887    113.9887
           ...
24645    131.8460
12952    123.6610
6864     147.5959
13606    130.6229
8203     142.6142
Name: Weight(Pounds), Length: 5000, dtype: float64

In [ ]:
from sklearn.metrics import r2_score,mean_absolute_error
r2_score(y_test, y_pred)

0.26145766094365497

In [ ]:
mean_absolute_error(y_test, y_pred)

7.918916609743709